spring:
  cloud:
    consul:
      service-registry:
        enabled: false
      discovery:
        enabled: false
    service-registry:
      enabled: false
      auto-registration:
        enabled: false
  application:
    name: grpc
grpc:
  server:
    port: 6565